---
title: "Talks & Posters"
---

## Talks

### 2025:
- Fast M-Estimation for Exploratory Generalized Linear Latent Variable Models (Invited) <p class="text-primary"> *Data Analytics Lab Workshop 2025, Ovronnaz, Switzerland. May, 2025.*
- A {lavaan} Extension for fast pairwise likelihood estimation of factor models for categorical data <p class="text-primary"> *Psychoco 2025, Ghent, Belgium, February, 2025.*
<p><div>
<button type="button" class="btn btn-outline-primary">[R Package ](https://giuseppealfonzetti.github.io/lavaan.pl/)</button>  
</div>
### 2024:
- Pairwise stochastic approximation for confirmatory factor analysis of categorical data (Invited)<p class="text-primary"> *CCDA2024, London, UK, October, 2024.*
- Pairwise stochastic approximation for confirmatory factor analysis of categorical data <p class="text-primary"> *IMPS2024, Prague, Czech Republic, July, 2024.* <p><div>
<button type="button" class="btn btn-outline-primary">[slides](https://github.com/giuseppealfonzetti/giuseppealfonzetti.github.io/raw/main/resources/slides/alfonzetti_IMPS2024.pdf)</button>  
</div>

- Scalable bootstrap inference via averaged Robbins-Monro approximations. <p class="text-primary"> *SDS2024, Palermo, Italy, April, 2024.* <p>

### 2023:
- Enhancing public decision making via large-scale graphical model <p class="text-primary"> *AQMAPPS2023, Milano, Italy, October, 2023.* <p>
- Propensity towards master's degree: choices of northern students after bas? <p class="text-primary"> *CLADAG2023, Salerno, Italy, September, 2023.* <p>
- Efficient stochastic learning of graphical structures for large-scale mixed data surveys. <p class="text-primary"> *IWSM2023, Dortmund, Germany, July, 2023.* <p>

### 2022:
- A stochastic optimisation algorithm for pairwise likelihood estimation of factor models with ordinal data. (Invited) <p class="text-primary"> *COMPSTAT2022 , Bologna, Italy. August, 2022.* <p>

- Some advances on pairwise likelihood estimation in ordinal data latent variable models. <p class="text-primary">*SIS2022, Caserta, Italy. June, 2022.*<p>

## Posters
### 2022:
- A stochastic optimization algorithm for pairwise likelihood estimation of factor models with ordinal data. **Alfonzetti, G.**, Bellio, R., Chen Y., Moustaki, I. <p class="text-primary">*Statistical methods and models for complex data, Padua, Italy. September, 2022.*<p>

- Reliable generalized linear latent variable models estimation via simulated maximum likelihood. **Alfonzetti, G.**, Bellio, R. <p class="text-primary">*IWSM, Trieste, Italy. July, 2022.*<p>

## Seminars
### 2022:
- On the estimation of latent trait models. <p class="text-primary">*Social Statistics meetings, London School of Economics, London, UK. February 17, 2022.*<p>
